// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockKSNOracleAdapter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockKSNOracleAdapter";
  readonly sourceName: "src/MockKSNOracleAdapter.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"assetId","type":"bytes32"}],"name":"ksnScore","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"name":"scores","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"assetId","type":"bytes32"},{"internalType":"uint256","name":"score","type":"uint256"}],"name":"setScore","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x608060405234801561000f575f80fd5b506101118061001d5f395ff3fe6080604052348015600e575f80fd5b5060043610603a575f3560e01c80635b36ac1c14603e57806389d9db9d14606c5780639711cacc14608a575b5f80fd5b605a604936600460a6565b5f6020819052908152604090205481565b60405190815260200160405180910390f35b6088607736600460bc565b5f9182526020829052604090912055565b005b605a609536600460a6565b5f9081526020819052604090205490565b5f6020828403121560b5575f80fd5b5035919050565b5f806040838503121560cc575f80fd5b5050803592602090910135915056fea264697066735822122000e727c06b5d079815f3af6ce13259c2033f073bb440bf5f704ab43e39f0700264736f6c63430008180033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b5060043610603a575f3560e01c80635b36ac1c14603e57806389d9db9d14606c5780639711cacc14608a575b5f80fd5b605a604936600460a6565b5f6020819052908152604090205481565b60405190815260200160405180910390f35b6088607736600460bc565b5f9182526020829052604090912055565b005b605a609536600460a6565b5f9081526020819052604090205490565b5f6020828403121560b5575f80fd5b5035919050565b5f806040838503121560cc575f80fd5b5050803592602090910135915056fea264697066735822122000e727c06b5d079815f3af6ce13259c2033f073bb440bf5f704ab43e39f0700264736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/MockKSNOracleAdapter.sol";
  readonly buildInfoId: "solc-0_8_24-0d721fbbb9c6edf6aa1e02ab645114a0996c4665";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockKSNOracleAdapter"]: MockKSNOracleAdapter$Type;
    ["src/MockKSNOracleAdapter.sol:MockKSNOracleAdapter"]: MockKSNOracleAdapter$Type;
  }
}